config/routes.rb
#        destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#           new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#          edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#               user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                             PUT    /users/password(.:format)                                                                devise/passwords#update
#                             POST   /users/password(.:format)                                                                devise/passwords#create
#    cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#       new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#      edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#           user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                             PUT    /users(.:format)                                                                         devise/registrations#update
#                             DELETE /users(.:format)                                                                         devise/registrations#destroy
#                             POST   /users(.:format)                                                                         devise/registrations#create
#          authenticated_root GET    /                                                                                        welcome#index
#        unauthenticated_root GET    /                                                                                        devise/sessions#new
#                    tab_show GET    /tab/show(.:format)                                                                      tab#show
#                  tab_create GET    /tab/create(.:format)                                                                    tab#create
#               welcome_index GET    /welcome/index(.:format)                                                                 welcome#index
#                  song_notes GET    /songs/:song_id/notes(.:format)                                                          notes#index
#                             POST   /songs/:song_id/notes(.:format)                                                          notes#create
#               new_song_note GET    /songs/:song_id/notes/new(.:format)                                                      notes#new
#              edit_song_note GET    /songs/:song_id/notes/:id/edit(.:format)                                                 notes#edit
#                   song_note GET    /songs/:song_id/notes/:id(.:format)                                                      notes#show
#                             PATCH  /songs/:song_id/notes/:id(.:format)                                                      notes#update
#                             PUT    /songs/:song_id/notes/:id(.:format)                                                      notes#update
#                             DELETE /songs/:song_id/notes/:id(.:format)                                                      notes#destroy
#                       songs GET    /songs(.:format)                                                                         songs#index
#                artist_songs GET    /artists/:artist_id/songs(.:format)                                                      songs#index
#                             POST   /artists/:artist_id/songs(.:format)                                                      songs#create
#             new_artist_song GET    /artists/:artist_id/songs/new(.:format)                                                  songs#new
#            edit_artist_song GET    /artists/:artist_id/songs/:id/edit(.:format)                                             songs#edit
#                 artist_song GET    /artists/:artist_id/songs/:id(.:format)                                                  songs#show
#                             PATCH  /artists/:artist_id/songs/:id(.:format)                                                  songs#update
#                             PUT    /artists/:artist_id/songs/:id(.:format)                                                  songs#update
#                             DELETE /artists/:artist_id/songs/:id(.:format)                                                  songs#destroy
#                     artists GET    /artists(.:format)                                                                       artists#index
#                             POST   /artists(.:format)                                                                       artists#create
#                  new_artist GET    /artists/new(.:format)                                                                   artists#new
#                 edit_artist GET    /artists/:id/edit(.:format)                                                              artists#edit
#                      artist GET    /artists/:id(.:format)                                                                   artists#show
#                             PATCH  /artists/:id(.:format)                                                                   artists#update
#                             PUT    /artists/:id(.:format)                                                                   artists#update
#                             DELETE /artists/:id(.:format)                                                                   artists#destroy
#     resource_resource_notes GET    /resources/:resource_id/resource_notes(.:format)                                         resource_notes#index
#                             POST   /resources/:resource_id/resource_notes(.:format)                                         resource_notes#create
#  new_resource_resource_note GET    /resources/:resource_id/resource_notes/new(.:format)                                     resource_notes#new
# edit_resource_resource_note GET    /resources/:resource_id/resource_notes/:id/edit(.:format)                                resource_notes#edit
#      resource_resource_note GET    /resources/:resource_id/resource_notes/:id(.:format)                                     resource_notes#show
#                             PATCH  /resources/:resource_id/resource_notes/:id(.:format)                                     resource_notes#update
#                             PUT    /resources/:resource_id/resource_notes/:id(.:format)                                     resource_notes#update
#                             DELETE /resources/:resource_id/resource_notes/:id(.:format)                                     resource_notes#destroy
#                   resources GET    /resources(.:format)                                                                     resources#index
#                             POST   /resources(.:format)                                                                     resources#create
#                new_resource GET    /resources/new(.:format)                                                                 resources#new
#               edit_resource GET    /resources/:id/edit(.:format)                                                            resources#edit
#                    resource GET    /resources/:id(.:format)                                                                 resources#show
#                             PATCH  /resources/:id(.:format)                                                                 resources#update
#                             PUT    /resources/:id(.:format)                                                                 resources#update
#                             DELETE /resources/:id(.:format)                                                                 resources#destroy
#                        root GET    /                                                                                        welcome#index
#          rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#   rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#          rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#   update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#        rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  get 'song_searches/index'
  get 'song_searches/show'
  get 'searches/index'
  get 'searches/show'
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'welcome#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get 'tab/show'
  get 'tab/create'
  get 'welcome/index'

  resources :songs, only: [:index] do
    resources :notes
  end

  resources :artists do
    resources :songs
  end

  resources :resources do
    resources :resource_notes
  end

  root 'welcome#index'

app/models/artist.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: artists
#
#  id         :bigint(8)        not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint(8)
#  spotify_id :string(255)
#  photo      :string(255)
#

class Artist < ApplicationRecord
  belongs_to :user

  has_many :songs, dependent: :destroy
  accepts_nested_attributes_for :songs
  validates :name, presence: true, uniqueness: true
end

app/controllers/artists_controller.rb
# frozen_string_literal: true

class ArtistsController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @artists = Artist.all.order("#{sort_column} #{sort_direction}")
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def new
    @artist = Artist.new
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def create
    @artist = Artist.new(artist_params)
    @artist.user = current_user

    if @artist.save
      redirect_to @artist
    else
      render 'new'
    end
  end

  def update
    @artist = Artist.find(params[:id])
    @artist.user = current_user

    if @artist.update(artist_params)
      redirect_to @artist
    else
      render 'edit'
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    redirect_to artists_path
  end

  private

  def sortable_columns
    ['name']
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : 'name'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def artist_params
    params.require(:artist).permit(:name, :user_id, :spotify_id, :photo)
  end
end

app/helpers/artists_helper.rb
# frozen_string_literal: true

module ArtistsHelper
  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    icon = sort_direction == 'asc' ? "<i class='fas fa-sort-up'></i>" : "<i class='fas fa-sort-down'></i>"
    icon = column == sort_column ? icon : ''
    link_to "#{title} #{icon}".html_safe, column: column, direction: direction
  end
end

app/views/artists/_form.html.erb
<%= form_with model: @artist, local: true do |form| %>
 
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@artist.errors.count, "error") %> prohibited
        this artist from being saved:
      </h2>
      <ul>
        <% @artist.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :spotify_id %><br>
    <%= form.text_field :spotify_id %>
  </p>
 
  <p>
    <%= form.submit class: 'btn' %>
  </p>
 
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render 'form' %>
 
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<div class="header row">
    <div class="col-md-6">
        <h1>Artists</h1>
    </div>
    <div class="col-md-3">
            <%= form_tag searches_index_path, method: "get", class: "search form-inline" do %>
              <%= text_field_tag(:search, "", placeholder: "Search Spotify for Artist", class: "form-control") %>
              <%= submit_tag "Search", class: "btn btn-primary" %>
            <% end %>
    </div>
    <div class="col-md-3">
            <%= link_to 'New Artist', new_artist_path, class: :btn %>
    </div>
</div>

<div class="row">
    <div class="col-md-8 all-artist-list">
        <table class="table-hover">
            <tr>
                <th></th>
                <th><%= sort_link "name" %></th>
                <th># Songs</th>
                <th colspan='3'></th>
            </tr>

            <% @artists = @artists.order('name') %>
            <% @artists.each do |artist| %>
                <tr>
                    <td><img height="50" width="50" src="<%= artist.photo %>"/></td>
                    <td><%= link_to artist.name, artist_path(artist) %></td>
                    <td><%= artist.songs.count %></td>
                    <td><%= link_to edit_artist_path(artist) do %>
                    <i class="fas fa-pencil-alt"></i>
                    <% end %>
                    <%= link_to artist_path(artist),
                            method: :delete,
                            data: { confirm: 'Are you sure?' } do %>
                            <i class="fas fa-times"></i>
                    <% end %></td>
                </tr>
            <% end %>
        </table>
    </div>
</div>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form' %>

<%= link_to 'Cancel', artists_path %>

app/views/artists/show.html.erb
<div class="header row">
  <div class="col-md-12 artist_header" style="background-image: url(<%= @artist.photo %>);">
      <h1><%= @artist.name %></h1>
      <a class="spotify" href="https://open.spotify.com/artist/<%= @artist.spotify_id %>" target="_blank"><i class="fab fa-spotify"></i></a>
      <%= link_to 'Edit', edit_artist_path(@artist) %>
  </div>
</div>
<div class="row songs_list">
  <div class="col-md-8">
    <h2>Songs</h2>
    <table class="table-hover">
      <% if @artist.songs.present? %>
        <% @artist.songs.each do |song| %>
          <tr>
            <td><%= link_to song.title, artist_song_path(@artist,song) %></td>
            <td><% if song.status? %>
                  <%= song.status.titlecase %>
                <% end %></td>
            <td><% if song.difficulty.present? %>
                  <% song.difficulty.to_i.times do  %>
                    <i class="fas fa-star"></i>
                  <% end %>
                  <% song.blank_stars.times do %>
                    <i class="far fa-star"></i>
                  <% end %>
                <% end %>
            </td>
            <td><% if song.tab.attached? %>
                  <i class="far fa-file"></i>
                <% end %>
                <% if song.spotify_url.present? %>
                  <i class="fab fa-spotify"></i>
                <% end %>
                <% if song.video_url.present? %>
                  <i class="fab fa-youtube"></i>
                <% end %>
            </td>
            <td><%= link_to edit_artist_song_path(@artist,song) do %>
                  <i class="fas fa-pencil-alt"></i>
                <% end %>
                <%= link_to [song.artist, song],
                        method: :delete,
                        data: { confirm: 'Are you sure?' } do %>
                        <i class="fas fa-times"></i>
                <% end %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <td>This artist has no songs.</td>
      <% end %>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <h2>Search for a song:</h2>

    <form class="song-search-form search" accept-charset="UTF-8">
          <input name="utf8" type="hidden" value="✓">
          <p>
            <input type="text" name="search" id="song-search" value="" placeholder="Seach song name" class="form-control">
          </p>
          <input type="hidden" name="artist_id" id="artist_id" value="<%= @artist.id %>">
    </form>

    <table class="search-results table-hover">
      <tbody></tbody>
    </table>
  </div>

  <div class="col-md-4">
    <h2>Or add song manually:</h2>

    <%= form_with(model: [ @artist, @artist.songs.build ], local: true) do |form| %>
      <p>
        <%= form.label :title %><br>
        <%= form.text_field :title, required: :true, class: "form-control" %>
      </p>
      <p>
        <%= form.label :tab %><br>
        <%= form.file_field :tab, multiple: false, direct_upload: true %>
      </p>
      <p>
        <%= form.label :status%><br>
        <%= form.select :status, Song.statuses.keys.map { |m| [m.titlecase, m]} %>
      </p>
      <p>
          <%= form.label :instrument %><br>
          <%= form.select :instrument, Song.instruments.keys.map { |m| [m.titlecase, m]} %>
      </p>
      <p>
          <%= form.label :difficulty %><br>
          <%= form.select :difficulty, (0..5).each { |m| [m]} %></br>
          1 = Beginner, 5 = Advanced
      </p>
      <p>
          <%= form.label :video %><br>
          <%= form.text_field :video_url, class: "form-control" %></br>
          Enter embed code (i.e. if URL is https://www.youtube.com/watch?v=2CYKtIu2oro, enter 2CYKtIu2oro)
      </p>
      <p>
          <%= form.label :spotify %><br>
          <%= form.text_field :spotify_url, class: "form-control" %></br>
          Enter embed code (i.e. if URL is https://open.spotify.com/embed/track/5ihS6UUlyQAfmp48eSkxuQ, enter 5ihS6UUlyQAfmp48eSkxuQ)
      </p>
      <p>
        <%= form.submit 'Submit', :class => 'btn' %>
      </p>
    <% end %>
  </div>

</div>